name: "Setup TestLens"
description: "Performs TestLens setup"
branding:
  color: green
  icon: eye

inputs:
  github-token:
    description: "The GitHub token used for authentication"
    required: true
    default: ${{ github.token }}
  instrumentation-version:
    description: "The version of app.testlens:junit-platform-instrumentation to use"
    required: true
    default: "1.7.0"
  write-log-files:
    description: "Writes diagnostic output to log files"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup TestLens
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        TESTLENS_PROJECT_ID: ${{ github.repository }}
        TESTLENS_GITHUB_TOKEN: ${{ inputs.github-token }}
        INSTRUMENTATION_VERSION: ${{ inputs.instrumentation-version }}
        RUNNER_OS: ${{ runner.os }}
        JOB_CHECK_RUN_ID: ${{ job.check_run_id }}
        WORKSPACE_PATH: ${{ github.workspace }}
        WRITE_LOG_FILES: ${{ inputs.write-log-files }}
      run: |
        # Setup TestLens

        # Add Gradle init script
        if [[ -n "$GRADLE_USER_HOME" ]]; then
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            WORKSPACE_PATH=$(echo "$WORKSPACE_PATH" | sed 's|\\|/|g')
            GRADLE_USER_HOME=$(echo "$GRADLE_USER_HOME" | sed 's|\\|/|g')
          fi
          echo -n $TESTLENS_GITHUB_TOKEN > $GRADLE_USER_HOME/init.d/TESTLENS_GITHUB_TOKEN
          echo -n $JOB_CHECK_RUN_ID > $GRADLE_USER_HOME/init.d/JOB_CHECK_RUN_ID
          cat << EOF > $GRADLE_USER_HOME/init.d/testlens-init.gradle
        import org.gradle.api.provider.*;
        gradle.beforeProject { project ->
          String relativeBuildPath = new File('$WORKSPACE_PATH').relativePath(project.rootDir)
          if (!relativeBuildPath.startsWith('..') && !new File(relativeBuildPath).isAbsolute()) {
            TestLensSetup.configure(project, relativeBuildPath)
          }
        }
        abstract class TestLensGitHubTokenValueSource implements ValueSource<String, ValueSourceParameters.None> {
          String obtain() { new File('$GRADLE_USER_HOME/init.d/TESTLENS_GITHUB_TOKEN').text }
        }
        abstract class TestLensJobCheckRunIdValueSource implements ValueSource<String, ValueSourceParameters.None> {
          String obtain() { new File('$GRADLE_USER_HOME/init.d/JOB_CHECK_RUN_ID').text }
        }
        final class TestLensSetup {
          static def configure(Project project, String relativeBuildPath) {
            project.plugins.withId('java') {
              project.testing.suites.configureEach {
                dependencies { runtimeOnly('app.testlens:junit-platform-instrumentation:$INSTRUMENTATION_VERSION') }
              }
            }
            def providers = project.providers
            project.tasks.withType(Test).configureEach { task ->
              def muteMarker = new File(task.temporaryDir, 'testlens-mute.marker')
              def logsDir = new File(task.temporaryDir, 'testlens-logs')
              def workUnitPath = task.path + (relativeBuildPath.isEmpty() ? '' : ' [' + relativeBuildPath + ']')
              task.environment('TESTLENS_PROJECT_ID', '$TESTLENS_PROJECT_ID')
              task.environment('TESTLENS_WORK_UNIT_PATH', workUnitPath)
              task.environment('TESTLENS_MUTE_MARKER_FILE', muteMarker.absolutePath)
              task.environment('TESTLENS_GITHUB_TOKEN', providers.of(TestLensGitHubTokenValueSource){}.get())
              task.environment('JOB_CHECK_RUN_ID', providers.of(TestLensJobCheckRunIdValueSource){}.get())
              if ('true'.equalsIgnoreCase('$WRITE_LOG_FILES')) {
                task.environment('TESTLENS_LOGS_DIR', logsDir.absolutePath)
              }
              task.filter.failOnNoMatchingTests = false
              if (task.hasProperty('failOnNoDiscoveredTests')) task.failOnNoDiscoveredTests = false
              task.addTestListener(new TestListener() {
                void beforeTest(TestDescriptor __) {}
                void afterTest(TestDescriptor __, TestResult ___) {}
                void beforeSuite(TestDescriptor __) {}
                void afterSuite(TestDescriptor __, TestResult ___) {
                  if (muteMarker.isFile()) {
                    task.outputs.doNotStoreInCache()
                    muteMarker.delete()
                  }
                }
              })
            }
          }
        }
        EOF
        fi

        # Patch Maven Parent POM
        if [[ -f "pom.xml" ]]; then
          POM_FILE="pom.xml"
          PROFILE_CONTENT="    <profile>
              <id>testlens</id>
              <activation>
                <property>
                  <name>env.CI</name>
                </property>
              </activation>
              <dependencies>
                <dependency>
                  <groupId>app.testlens</groupId>
                  <artifactId>junit-platform-instrumentation</artifactId>
                  <version>$INSTRUMENTATION_VERSION</version>
                  <scope>test</scope>
                </dependency>
              </dependencies>
              <build>
                <plugins>
                  <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <configuration>
                      <environmentVariables>
                        <TESTLENS_PROJECT_ID>$TESTLENS_PROJECT_ID</TESTLENS_PROJECT_ID>
                        <TESTLENS_GITHUB_TOKEN>$TESTLENS_GITHUB_TOKEN</TESTLENS_GITHUB_TOKEN>
                        <TESTLENS_WORK_UNIT_PATH>\${project.name}</TESTLENS_WORK_UNIT_PATH>
                        <JOB_CHECK_RUN_ID>$JOB_CHECK_RUN_ID</JOB_CHECK_RUN_ID>
                      </environmentVariables>
                    </configuration>
                  </plugin>
                  <plugin>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <configuration>
                      <environmentVariables>
                        <TESTLENS_PROJECT_ID>$TESTLENS_PROJECT_ID</TESTLENS_PROJECT_ID>
                        <TESTLENS_GITHUB_TOKEN>$TESTLENS_GITHUB_TOKEN</TESTLENS_GITHUB_TOKEN>
                        <TESTLENS_WORK_UNIT_PATH>\${project.name}</TESTLENS_WORK_UNIT_PATH>
                        <JOB_CHECK_RUN_ID>$JOB_CHECK_RUN_ID</JOB_CHECK_RUN_ID>
                      </environmentVariables>
                    </configuration>
                  </plugin>
                </plugins>
              </build>
            </profile>"
          CLOSING_PROFILES_TAG_LINE=$({ grep -n "</profiles>" "$POM_FILE" || true; } | tail -1 | cut -d: -f1)
          CLOSING_PROJECT_TAG_LINE=$({ grep -n "</project>" "$POM_FILE" || true; } | tail -1 | cut -d: -f1)
          if [ -n "$CLOSING_PROFILES_TAG_LINE" ]; then
            {
              head -n $((CLOSING_PROFILES_TAG_LINE - 1)) "$POM_FILE"
              echo "$PROFILE_CONTENT"
              tail -n +$CLOSING_PROFILES_TAG_LINE "$POM_FILE"
            } > "${POM_FILE}.tmp"
            mv "${POM_FILE}.tmp" "$POM_FILE"
          elif [ -n "$CLOSING_PROJECT_TAG_LINE" ]; then
            {
              head -n $((CLOSING_PROJECT_TAG_LINE - 1)) "$POM_FILE"
              echo ""
              echo "  <profiles>"
              echo "$PROFILE_CONTENT"
              echo "  </profiles>"
              tail -n +$CLOSING_PROJECT_TAG_LINE "$POM_FILE"
            } > "${POM_FILE}.tmp"
            mv "${POM_FILE}.tmp" "$POM_FILE"
          fi
        fi
