name: "Setup TestLens"
description: "Performs TestLens setup"
inputs:
  github-token:
    description: "The GitHub token used for authentication"
    required: true
    default: ${{ github.token }}
  instrumentation-version:
    description: "The version of app.testlens:junit-platform-instrumentation to use"
    required: true
    default: "1.0.0"

runs:
  using: "composite"
  steps:
    - name: Export Workspace Path
      shell: bash
      run: echo "WORKSPACE_PATH=$(echo ${{ github.workspace }})" >> $GITHUB_ENV
    - name: Escape Workspace Path
      if: runner.os == 'Windows'
      shell: bash
      run: echo "WORKSPACE_PATH=$(echo ${{ github.workspace }} | sed 's|\\|/|g')" >> $GITHUB_ENV
    - name: Add Gradle init script
      shell: bash
      run: |
        cat << 'EOF' > $GRADLE_USER_HOME/init.d/testlens-init.gradle
        gradle.allprojects {
          if (new File('${{ env.WORKSPACE_PATH }}').absoluteFile == rootProject.projectDir.absoluteFile) {
            def isPR = System.getenv('GITHUB_REF_NAME')?.endsWith('/merge')?:false
            def attempt = System.getenv('GITHUB_RUN_ATTEMPT')?.toInteger()?:1
            def disableCache = isPR && attempt > 1
            plugins.withId('java') {
              testing.suites.configureEach {
                dependencies { runtimeOnly('app.testlens:junit-platform-instrumentation:${{ inputs.instrumentation-version }}') }
              }
            }
            tasks.withType(Test).configureEach { task ->
              def systemProperties = [
                '-Dapp.testlens.project-id=${{ github.repository }}',
                '-Dapp.testlens.github-token=${{ inputs.github-token }}',
                "-Dapp.testlens.work-unit-path=${task.path}"
              ]
              task.jvmArgumentProviders.add({systemProperties} as CommandLineArgumentProvider)
              if (disableCache) {
                task.outputs.doNotCacheIf("Potentially contains tests muted by TestLens") { true }
              }
            }
          }
        }
        EOF
