name: "Setup TestLens"
description: "Performs TestLens setup"
inputs:
  token:
    description: "Token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Add Gradle init script
      shell: bash
      run: |
        cat << 'EOF' > $GRADLE_USER_HOME/init.d/testlens-init.gradle
        gradle.allprojects {
          if (new File('${{ github.workspace }}').absolutePath == rootProject.projectDir.absolutePath) {
            def isPR = System.getenv('GITHUB_REF_NAME')?.endsWith('/merge')?:false
            def attempt = System.getenv('GITHUB_RUN_ATTEMPT')?.toInteger()?:1
            def disableCache = isPR && attempt > 1
            plugins.withId('java') {
              testing.suites.configureEach {
                dependencies { runtimeOnly('app.testlens:junit-platform-instrumentation:0.1.0-SNAPSHOT') }
              }
            }
            tasks.withType(Test).configureEach {
              systemProperty('app.testlens.project-id', '${{ github.repository }}')
              systemProperty('app.testlens.token', '${{ inputs.token }}')
              if (disableCache) {
                outputs.doNotCacheIf("Potentially contains tests muted by TestLens") { true }
              }
            }
          }
        }
        EOF

        # Escape windows paths stored in GitHub variables
        sed -i 's|\\|/|g' $GRADLE_USER_HOME/init.d/testlens-init.gradle
