name: "Set up TestLens"
description: "Performs TestLens setup"
branding:
  color: green
  icon: eye

inputs:
  github-token:
    description: "The GitHub token used for authentication"
    required: true
    default: ${{ github.token }}
  instrumentation-version:
    description: "The version of app.testlens:junit-platform-instrumentation to use"
    required: true
    default: "1.9.2"
  write-log-files:
    description: "Writes diagnostic output to log files (**/testlens-logs/*.log)"
    required: false
    default: "false"
  session-timeout-seconds:
    description: "The timeout (in seconds) to use when waiting for a session to be completed"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up TestLens
      env:
        TESTLENS_PROJECT_ID: ${{ github.repository }}
        TESTLENS_GITHUB_TOKEN: ${{ inputs.github-token }}
        INSTRUMENTATION_VERSION: ${{ inputs.instrumentation-version }}
        RUNNER_OS: ${{ runner.os }}
        JOB_CHECK_RUN_ID: ${{ job.check_run_id }}
        WORKSPACE_PATH: ${{ github.workspace }}
        WRITE_LOG_FILES: ${{ inputs.write-log-files }}
        SESSION_TIMEOUT_SECONDS: ${{ inputs.session-timeout-seconds }}
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        # Set up TestLens
        ${{ github.action_path }}/setup-testlens.sh
