name: "Setup TestLens"
description: "Performs TestLens setup"
inputs:
  github-token:
    description: "The GitHub token used for authentication"
    required: true
    default: ${{ github.token }}
  instrumentation-version:
    description: "The version of app.testlens:junit-platform-instrumentation to use"
    required: true
    default: "1.4.0"
  write-log-files:
    description: "Writes diagnostic output to log files"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Add Gradle init script
      shell: bash
      env:
        TESTLENS_PROJECT_ID: ${{ github.repository }}
        TESTLENS_GITHUB_TOKEN: ${{ inputs.github-token }}
        INSTRUMENTATION_VERSION: ${{ inputs.instrumentation-version }}
        RUNNER_OS: ${{ runner.os }}
        WORKSPACE_PATH: ${{ github.workspace }}
        WRITE_LOG_FILES: ${{ inputs.write-log-files }}
      run: |
        # Add Gradle init script
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          WORKSPACE_PATH=$(echo "$WORKSPACE_PATH" | sed 's|\\|/|g')
        fi
        cat << EOF > $GRADLE_USER_HOME/init.d/testlens-init.gradle
        gradle.beforeProject { project ->
          TestLensSetup.configure(project)
        }
        class TestLensSetup {
          static def configure(Project project) {
            String relativeBuildPath = new File('$WORKSPACE_PATH').relativePath(project.rootDir)
            project.plugins.withId('java') {
              project.testing.suites.configureEach {
                dependencies { runtimeOnly('app.testlens:junit-platform-instrumentation:$INSTRUMENTATION_VERSION') }
              }
            }
            project.tasks.withType(Test).configureEach { task ->
              def muteMarker = new File(task.temporaryDir, 'testlens-mute.marker')
              def logsDir = new File(task.temporaryDir, 'testlens-logs')
              def workUnitPath = task.path + (relativeBuildPath.isEmpty() ? '' : ' [' + relativeBuildPath + ']')
              task.environment('TESTLENS_PROJECT_ID', '$TESTLENS_PROJECT_ID')
              task.environment('TESTLENS_GITHUB_TOKEN', '$TESTLENS_GITHUB_TOKEN')
              task.environment('TESTLENS_WORK_UNIT_PATH', workUnitPath)
              task.environment('TESTLENS_MUTE_MARKER_FILE', muteMarker.absolutePath)
              if ('true'.equalsIgnoreCase('$WRITE_LOG_FILES')) {
                task.environment('TESTLENS_LOGS_DIR', logsDir.absolutePath)
              }
              task.filter.failOnNoMatchingTests = false
              if (task.hasProperty('failOnNoDiscoveredTests')) task.failOnNoDiscoveredTests = false
              task.addTestListener(new TestListener() {
                void beforeTest(TestDescriptor __) {}
                void afterTest(TestDescriptor __, TestResult ___) {}
                void beforeSuite(TestDescriptor __) {}
                void afterSuite(TestDescriptor __, TestResult ___) {
                  if (muteMarker.isFile()) {
                    task.outputs.doNotStoreInCache()
                    muteMarker.delete()
                  }
                }
              })
            }
          }
        }
        EOF
