name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Version to be released (e.g. "1.7.2")
        required: true

permissions: {}

env:
  RELEASE_TAG: v${{ inputs.releaseVersion }}

jobs:
  release:
    name: Create tags and GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true # required for pushing tags in subsequent steps
      - name: Create version tag
        run: |
          git tag --annotate --message=$RELEASE_TAG $RELEASE_TAG
          git push origin tag $RELEASE_TAG
      - name: Move short version tag
        run: |
          SHORT_TAG=${RELEASE_TAG%%.*}
          git tag --annotate --message=SHORT_TAG --force $SHORT_TAG 
          git push --force origin tag $SHORT_TAG
      - name: Create GitHub release
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const createGithubRelease = require('./.github/scripts/create-github-release.js');
            createGithubRelease({ github, context, process.env.RELEASE_TAG });
